name: quarto-render

on:
  push:
    branches:
      - main

jobs:
  quarto-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: test.qmd
