name: Render and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkou@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - run: |
          quarto --version